# Generated by Django 3.2.16 on 2023-04-29 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduapp', '0021_teacherwithdescription'),
        ('courses', '0002_auto_20230430_0230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Курсы', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=100, verbose_name='Название курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(default='Описание', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='course',
            name='related_teachers',
            field=models.ManyToManyField(to='eduapp.TeacherWithDescription'),
        ),
    ]
