# Generated by Django 3.2.16 on 2023-04-29 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduapp', '0021_teacherwithdescription'),
        ('courses', '0003_auto_20230430_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='related_teachers',
            field=models.ManyToManyField(to='eduapp.Teacher'),
        ),
    ]
