# Generated by Django 3.2.16 on 2023-04-30 07:40

from django.db import migrations, models
import eduapp.storage
import optimized_image.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_related_teachers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='course',
            name='bg_image',
            field=optimized_image.fields.OptimizedImageField(blank=True, null=True, storage=eduapp.storage.OverwriteStorage(), upload_to='course_bgimages', verbose_name='Фоновое изображение'),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
