# Generated by Django 3.2.16 on 2023-04-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_coursetag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursetag',
            options={'verbose_name': 'Тэг', 'verbose_name_plural': 'Тэги'},
        ),
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.ManyToManyField(to='courses.CourseTag', verbose_name='Тэги'),
        ),
    ]
