# Generated by Django 3.2.16 on 2023-04-30 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eduapp', '0025_auto_20230430_1249'),
        ('courses', '0008_alter_course_related_teachers'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTeachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduapp.teacher')),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='related_teachers',
            field=models.ManyToManyField(through='courses.CourseTeachers', to='eduapp.Teacher', verbose_name='Связанные учителя'),
        ),
        migrations.AddField(
            model_name='course',
            name='related_teachers',
            field=models.ManyToManyField(to='eduapp.Teacher',
                                         verbose_name='Связанные учителя'),
        ),
    ]
