# Generated by Django 3.2.16 on 2023-04-30 15:05

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20230430_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetag',
            name='color',
            field=colorfield.fields.ColorField(default='#2C3E50', image_field=None, max_length=18, samples=None),
        ),
    ]
