# Generated by Django 3.2.16 on 2023-04-30 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_coursetag_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='subject',
        ),
    ]
