# Generated by Django 3.2.16 on 2023-05-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_remove_course_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursetag',
            options={'ordering': ['order_by'], 'verbose_name': 'Тэг', 'verbose_name_plural': 'Тэги'},
        ),
        migrations.AddField(
            model_name='coursetag',
            name='order_by',
            field=models.IntegerField(default=1, verbose_name='Приоритет'),
        ),
    ]
