# Generated by Django 3.2.16 on 2023-05-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_alter_course_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetag',
            name='title',
            field=models.CharField(max_length=50, unique=True, verbose_name='Тэг'),
        ),
    ]
