# Generated by Django 3.2.16 on 2023-05-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_alter_coursetag_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursetag',
            options={'ordering': ['order_by', 'title'], 'verbose_name': 'Тэг', 'verbose_name_plural': 'Тэги'},
        ),
        migrations.AlterField(
            model_name='coursetag',
            name='title',
            field=models.CharField(max_length=50, unique=True, verbose_name='Имя тэга'),
        ),
    ]
