# Generated by Django 3.2.16 on 2023-05-01 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_auto_20230501_1701'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='course',
            order_with_respect_to='tags',
        ),
    ]
