# Generated by Django 3.2.16 on 2023-05-01 14:19

from django.db import migrations
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_alter_course_order_with_respect_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursetag',
            options={'ordering': ['order_by', 'title', django.db.models.expressions.F('title')], 'verbose_name': django.db.models.expressions.F('title'), 'verbose_name_plural': 'Тэги'},
        ),
        migrations.AlterOrderWithRespectTo(
            name='course',
            order_with_respect_to=None,
        ),
    ]
