# Generated by Django 3.2.16 on 2023-05-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_auto_20230501_2132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonlist',
            options={'verbose_name': 'Список уроков', 'verbose_name_plural': 'Список уроков'},
        ),
        migrations.AlterField(
            model_name='lessonlist',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
