# Generated by Django 3.2.16 on 2023-05-01 18:24

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_auto_20230501_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonlist',
            name='related_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course'),
        ),
        migrations.AlterField(
            model_name='lessonlist',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='courses.lessonlist', verbose_name='Родитель'),
        ),
        migrations.AlterField(
            model_name='lessonlist',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
