# Generated by Django 3.2.16 on 2023-05-01 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_auto_20230501_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonlist',
            name='related_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course', verbose_name='Связанный курс'),
        ),
    ]
