# Generated by Django 3.2.16 on 2023-05-01 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_alter_lessonlist_related_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonlist',
            options={'ordering': ['related_course'], 'verbose_name': 'Список уроков', 'verbose_name_plural': 'Список уроков'},
        ),
    ]
