# Generated by Django 3.2.16 on 2023-05-01 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_alter_lessonlist_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonlist',
            options={'ordering': ['related_course__title'], 'verbose_name': 'Список уроков', 'verbose_name_plural': 'Список уроков'},
        ),
    ]
