# Generated by Django 3.2.16 on 2023-05-01 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_alter_lessonlist_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonlist',
            options={'verbose_name': 'Список уроков', 'verbose_name_plural': 'Список уроков'},
        ),
    ]
