# Generated by Django 3.2.16 on 2023-05-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_alter_lessonlist_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonlist',
            name='order_by',
            field=models.IntegerField(default=1, verbose_name='Приоритет'),
        ),
    ]
