# Generated by Django 4.2.6 on 2025-01-16 01:38

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0033_alter_lessonlist_lesson_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonlist',
            name='lesson_page',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
    ]
