# Generated by Django 4.2.6 on 2025-01-16 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0034_alter_lessonlist_lesson_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonlist',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
