# Generated by Django 3.2.16 on 2023-04-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gridsubject',
            options={'verbose_name': 'Предмет на главной', 'verbose_name_plural': 'Предметы на главной'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Название предмета', 'verbose_name_plural': 'Названия предметов'},
        ),
        migrations.AlterField(
            model_name='gridsubject',
            name='is_active',
            field=models.BooleanField(verbose_name='Активен'),
        ),
    ]
