# Generated by Django 3.2.16 on 2023-04-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduapp', '0003_alter_gridsubject_bg_text_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gridsubject',
            name='bg_image',
            field=models.ImageField(upload_to='media/', verbose_name='Фоновое изображение'),
        ),
        migrations.AlterField(
            model_name='gridsubject',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
    ]
