# Generated by Django 3.2.16 on 2023-04-27 13:01

import django.core.validators
from django.db import migrations, models
import eduapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('eduapp', '0004_auto_20230427_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gridsubject',
            name='bg_image',
            field=models.FileField(upload_to='media/', validators=[eduapp.models.validate_svg, django.core.validators.validate_image_file_extension], verbose_name='Фоновое изображение'),
        ),
    ]
