# Generated by Django 3.2.16 on 2023-04-27 14:31

from django.db import migrations, models
import eduapp.models
import eduapp.storage


class Migration(migrations.Migration):

    dependencies = [
        ('eduapp', '0008_rename_subject_id_gridsubject_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gridsubject',
            name='bg_image',
            field=models.FileField(storage=eduapp.storage.OverwriteStorage(), upload_to='images', validators=[eduapp.models.validate_svg], verbose_name='Фоновое изображение'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(max_length=50, verbose_name='Название предмета'),
        ),
    ]
