# Generated by Django 3.2.16 on 2023-04-28 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduapp', '0012_auto_20230429_0333'),
    ]

    operations = [
    ]
