# Generated by Django 3.2.16 on 2023-04-29 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eduapp', '0022_delete_teacherwithdescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherWithDescription',
            fields=[
                ('teacher_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='eduapp.teacher')),
            ],
            bases=('eduapp.teacher',),
        ),
    ]
