# Generated by Django 3.2.16 on 2023-04-29 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_related_teachers'),
        ('eduapp', '0023_teacherwithdescription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherWithDescription',
        ),
    ]
