# Generated by Django 3.2.16 on 2023-04-27 12:16

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduapp', '0002_auto_20230427_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gridsubject',
            name='bg_text_color',
            field=colorfield.fields.ColorField(default='#5FAFDC', image_field=None, max_length=18, samples=None, verbose_name='Цвет фона текста'),
        ),
    ]
