# Generated by Django 3.2.16 on 2023-04-27 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduapp', '0007_alter_gridsubject_bg_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gridsubject',
            old_name='subject_id',
            new_name='subject',
        ),
    ]
