# Generated by Django 3.2.16 on 2023-04-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduapp', '0010_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Учителя', 'verbose_name_plural': 'Учителя'},
        ),
        migrations.AlterField(
            model_name='teacher',
            name='description',
            field=models.TextField(max_length=50, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=50, verbose_name='ФИО'),
        ),
    ]
