# Generated by Django 3.2.16 on 2023-04-28 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduapp', '0013_transfer_bg_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gridsubject',
            name='bg_image',
        ),
    ]
