# Generated by Django 3.2.16 on 2023-04-29 21:52

from django.db import migrations, models
import eduapp.storage
import optimized_image.fields


class Migration(migrations.Migration):

    dependencies = [
        ('eduapp', '0017_auto_20230429_0423'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='on_index',
            field=models.BooleanField(default=False, verbose_name='Отображать на главной'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=optimized_image.fields.OptimizedImageField(storage=eduapp.storage.OverwriteStorage(), upload_to='teachers', verbose_name='Фото'),
        ),
    ]
